config/routes.rb
Rails.application.routes.draw do
  get 'ui(/:action)', controller: 'ui'

  root 'reviews#index'
  get '/home', to: 'reviews#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/register', to: 'users#new'
  resources :users, only: [:create, :show]

  resources :businesses, only: [:index, :new, :create, :show]

  resources :reviews, only: [:index, :create]

end

app/models/business.rb
class Business < ActiveRecord::Base
  has_many :reviews
  validates_presence_of :name
  validates_uniqueness_of :name
  validates_presence_of :description
  validates_presence_of :picture_url
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :business

  validates_presence_of :description
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reviews

  has_secure_password

  validates_presence_of :email
  validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  #Methods available everywhere
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  #Methods only available in controllers
  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to do that."
      redirect_to login_path
    end
  end

  if Rails.env.production?
    unless Rails.application.config.consider_all_requests_local
      rescue_from Exception, with: :render_500
    end
  end

  def render_500(exception)
    logger.info exception.backtrace.join("\n")
    respond_to do |format|
      format.html { render template: 'errors/internal_server_error', layout: 'layouts/application', status: 500 }
      format.all { render nothing: true, status: 500}
    end
  end
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  def new
    @business = Business.new
  end

  def create
    @business = Business.new(params[:business].permit(:name, :description, :picture_url))

    if @business.save
      flash[:success] = "New business listed!"
      redirect_to businesses_path
    else
      flash[:danger] = "There were some problems."
      render :new
    end
  end

  def index
    @col1 = []; @col2 = []; @col3 = []
    Business.all.each_slice(3) do |first, second, third|
      @col1.push(first) if first
      @col2.push(second) if second
      @col3.push(third) if third
    end
  end


  def show
    @business = Business.find(params[:id])
    @review = Review.new
    @reviews = @business.reviews.all if @business
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :require_user, except: [:index]

  def create
    review = Review.new(description: params[:review][:description],
                        business_id: params[:review][:business_id],
                        user_id: current_user.id)

    if review.save
      flash[:success] = "New review created!"
    else
      flash[:danger] = "There was a problem creating the review"
    end

    business = Business.find(params[:review][:business_id])
    redirect_to business_path(business)
  end

  def index
    @reviews = Review.all.order(:created_at).reverse.first(6)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to home_path if logged_in?
    @user = User.new #for bootstrap_form_for usage
  end

  def create
    user = User.find_by(email: params[:user][:email])
    if user && user.authenticate(params[:user][:password])
      session[:user_id] = user.id
      flash[:success] = "Welcome, you're logged in!"
      redirect_to home_path
    else
      flash[:danger] = "There was something wrong with your password or username."
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You've logged out."
    redirect_to root_path
  end
end

app/controllers/ui_controller.rb
class UiController < ApplicationController
  before_filter do
    redirect_to :root if Rails.env.production?
  end

  layout "application"

  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user].permit(:email, :full_name, :password))

    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "You've successfully registered and are now logged in. Welcome!"
      redirect_to home_path
    else
      flash[:danger] = "Oops, there were some problems."
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @reviews = @user.reviews.all if @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/businesses/index.html.haml
%article.business
  .row
    .col-md-3.col-md-offset-1
      %header
        %h1 Restaurants
  .row
    .col-md-3.col-md-offset-1
      - @col1.each do |business|
        .videos.row
          .col-sm-12
            = link_to "#{business.name}", business
          .video.col-sm-6
            = link_to "", nil do
              %img(src="#{business.picture_url}")
          %br
          .col-sm-12
            %p= business.description
        %hr
    .col-md-3.col-md-offset-1
      - @col2.each do |business|
        .videos.row
          .col-sm-12
            = link_to "#{business.name}", business
          .video.col-sm-6
            = link_to "", nil do
              %img(src="#{business.picture_url}")
          %br
          .col-sm-12
            %p= business.description
        %hr
    .col-md-3.col-md-offset-1
      - @col3.each do |business|
        .videos.row
          .col-sm-12
            = link_to "#{business.name}", business
          .video.col-sm-6
            = link_to "", nil do
              %img(src="#{business.picture_url}")
          .col-sm-12
            %p= business.description
        %hr

app/views/businesses/new.html.haml
%section.admin_add_video
  .container
    .row
      .col-md-10.col-md-offset-1
        = bootstrap_form_for @business, layout: :horizontal, control_col: "col-sm-6" do |f|
          %h3 Add a New Business
          %br
          %fieldset
            = f.text_field :name, label: "Business Name"
            = f.text_area :description
            = f.select :picture_url, [["Taco", "https://images.duckduckgo.com/iu/?u=http%3A%2F%2Fwww.foodpeoplewant.com%2Fwp-content%2Fuploads%2F2010%2F03%2FTacos-de-Barbacoa.jpg&f=1"],
                                      ["Pasta", "https://images.duckduckgo.com/iu/?u=http%3A%2F%2Fouritaliantable.com%2Fwp-content%2Fuploads%2F2010%2F06%2Fcrabmeat-pasta.jpg&f=1"],
                                      ["Pizza", "https://images.duckduckgo.com/iu/?u=http%3A%2F%2Fwww.denniscummins.com%2Fwp-content%2Fuploads%2F2010%2F10%2FSupreme_pizza.jpg&f=1"]],
              { label: "Choose a picture:" }, { class: "selectpicker" }
            = f.submit "List the Business", class: "btn btn-default col-sm-offset-2"

app/views/businesses/show.html.haml
%article.video
  .container
    .row
      .video_large_cover.col-sm-7.col-sm-offset-1
        %img(src="#{@business.picture_url}")
      .video_info.col-sm-3
        %header
          %h3= @business.name
        %p= @business.description

%section.reviews.container
  .row
    .col-sm-7.col-sm-offset-1
      = bootstrap_form_for @review do |f|
        = f.text_area :description, label: "Write Review", rows: 6
        = f.hidden_field :business, value: @business.id, name: "review[business_id]"
        = f.submit "Submit", class: "btn btn-default"
  .row
    .col-sm-10.col-sm-offset-1
      %header
        %h3= "User Reviews (#{@reviews.count})"
      %ul
        - @reviews.each do |review|
          %article.review
            %li.row
              .col-sm-2
                %p!= "by <a href=#{user_path(review.user)}>#{review.user.full_name}</a>"
              .col-sm-8
                %p= review.description

app/views/layouts/application.html.haml
!!! 5
%html
%head
  %title YelpClone
  = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
%body
  %header
    = render 'shared/header'
  %section.content.clearfix
    = render 'shared/messages'
    = yield
  %footer
    &copy 2015 Yelp_Practice_Clone

app/views/reviews/index.html.haml
%section.reviews.container
  .row
    .col-sm-8.col-sm-offset-1
      %header
        %h3 Recent Reviews
      %ul
        - @reviews.each do |review|
          %article.review
            %li.row
              .col-sm-3
                = link_to review.business.name, review.business
                %p!= "by <a href=#{user_path(review.user)}>#{review.user.full_name}</a>"
              .col-sm-6
                %p= review.description
              .col-sm-3
                %img(src="#{review.business.picture_url}")

app/views/shared/_header.html.haml
%section#top-header.row
  %h1.col-md-2.col-md-offset-2.main-header-logo
    = link_to "Yelp", root_path
  .col-md-4
    .row
      .col-md-12
        = form_tag "/#", class: "navbar-form", method: "get"  do
          %input.form-control(name="search_term" type="text" placeholder="Find food!")
          %button.btn.btn-default(type="submit") Search
    .row
      .col-md-12
        %ul.clearfix
          %li= link_to "All Businesses", businesses_path, class: :navlink
          %li= link_to "+ Add Business", new_business_path, class: :navlink
          %li= link_to "Recent Reviews", reviews_path, class: :navlink
          %li= link_to "My Profile", nil, class: :navlink
  .col-md-3
    #user_links.pull-right
      - if logged_in?
        %ul
          %li.dropdown
            %a(href="#" id="dlabel" role="button" data-toggle="dropdown" class="dropdown-toggle" data-target="#")
              = "Welcome, #{current_user.full_name}"
              %b.caret
            %ul.dropdown-menu(role="menu" aria-labelledby="dlabel")
              %li
                %a(href="#") Profile
                %a(href="#{logout_path}") Sign Out
      - else
        = link_to "Login", login_path, class: :navlink2
        = link_to "Register", register_path, class: :navlink2

app/views/shared/_messages.html.haml
- flash.each do |name, msg|
  %div(class="alert alert-#{name}")
    %a.close(data-dismiss='alert') &#215;
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/ui/index.html.haml
%section.ui-index
  %ul
    - Dir.glob('app/views/ui/*.html.haml').sort.each do |file|
      - wireframe = File.basename(file,'.html.haml')
      -  unless wireframe == 'index' || wireframe.match(/^_/)
        %li= link_to wireframe.titleize, action: wireframe unless wireframe == 'index'

app/views/ui/yelp_add_business.html.haml
%section.admin_add_video
  .container
    .row
      .col-md-10.col-md-offset-1
        %form.form-horizontal
          %h3 Add a New Business
          %br
          %fieldset
            .form-group
              %label.control-label.col-sm-3 Title
              .col-sm-3
                %input.form-control(type="text")
            .form-group
              %label.control-label.col-sm-3 Category
              .col-sm-6
                %select.form-control
            .form-group
              %label.control-label.col-sm-3 Description
              .col-sm-6
                %textarea.form-control(rows="8")
            .form-group
              %label.control-label.col-sm-3 Large Cover
              .col-sm-6
                %col.btn.btn-file
                  %input.form-control(type="file")
            .form-group
              %label.control-label.col-sm-3 Small Cover
              .col-sm-6
                %col.btn.btn-file
                  %input.form-control(type="file")

          %fieldset.actions.form-group
            .col-sm-6.col-md-offset-3
              %input(type="submit" value="Add Business" class="btn btn-default")

app/views/ui/yelp_businesses.html.haml
%article.business
  .row
    .col-md-3.col-md-offset-1
      %header
        %h3= link_to "Mexican Food"
      - 3.times do
        .videos.row
          .video.col-sm-6
            = link_to "", nil do
              %img(src="/assets/tacos.jpg")
          .review.col-sm-6
            %p Reviews (5/5)
          .col-sm-12
            %h6 Taco Restaurant
        %hr
    .col-md-3.col-md-offset-1
      %header
        %h3= link_to "Italian"
      - 3.times do
        .videos.row
          .video.col-sm-6
            = link_to "", nil do
              %img(src="/assets/pasta.jpeg")
          .review.col-sm-6
            %p Reviews (5/5)
          .col-sm-12
            %h6 Pasta Restaurant
        %hr
    .col-md-3.col-md-offset-1
      %header
        %h3= link_to "Pizza"
      - 3.times do
        .videos.row
          .video.col-sm-6
            = link_to "", nil do
              %img(src="/assets/pizza.jpeg")
          .review.col-sm-6
            %p Reviews (5/5)
          .col-sm-12
            %h6 Giordano's Restaurant
        %hr

app/views/ui/yelp_recent_reviews.html.haml
%section.reviews.container
  .row
    .col-sm-8.col-sm-offset-1
      %header
        %h3 Recent Reviews (253)
      %ul
        - 8.times do
          %article.review
            %li.row
              .col-sm-3
                = link_to "Taco Joint"
                %p by <a href="">John A. Zoidberg</a>
              .col-sm-6
                %p In my opinion, this is one of the best shows ever made. It's not only funny, but despite being so frequently silly, it's very smart as well. Math, science, history, all get referenced. The best parts of the show are the subtle things, those little things in the background or just on screen for a couple of seconds that just make you laugh out loud if you were paying attention. The writers even appear to have been thinking ahead, because if you play close attention to the first episode, you can see a literal shadow of an event revealed seasons later.
              .col-sm-3
                %img(src="/assets/tacos.jpg")

app/views/ui/yelp_register.html.haml
%section.register.container
  .row
    .col-sm-10.col-sm-offset-1
      %form.form-horizontal
        %header
          %h1 Register
        %fieldset
          .form-group
            %label.control-label.col-sm-2 Email Address
            .col-sm-6
              %input.form-control(type="email")
          .form-group
            %label.control-label.col-sm-2 Password
            .col-sm-6
              %input.form-control(type="password")
          .form-group
            %label.control-label.col-sm-2 Full Name
            .col-sm-6
              %input.form-control(type="text")
        %fieldset.actions.control-group.col-sm-offset-2
          .controls
            %input(type="submit" value="Sign Up" class="btn btn-default")

app/views/ui/yelp_reviews.html.haml
%article.video
  .container
    .row
      .video_large_cover.col-sm-7.col-sm-offset-1
        %img(src="/assets/tacos.jpg")
      .video_info.col-sm-3
        %header
          %h3 Futurama
        %p Pizza boy Philip J. Fry awakens in the 31st century after 1,000 years of cryogenic preservation in this animated series. After he gets a job at an interplanetary delivery service, Fry embarks on ridiculous escapades to make sense of his predicament.

%section.reviews.container
  .row
    .col-sm-10.col-sm-offset-1
      %form
        %fieldset
          .form-group
            %label Write Review
            .row
              .col-sm-8
                %textarea.form-control(name="" rows="6")
        %fieldset.form-group.actions.clearfix
          %input(type="submit" value="Submit" class="btn")
          %a(href="") Cancel
      %header
        %h3 User Reviews (253)
      %ul
        - 8.times do
          %article.review
            %li.row
              .col-sm-2
                %p by <a href="">John A. Zoidberg</a>
              .col-sm-8
                %p In my opinion, this is one of the best shows ever made. It's not only funny, but despite being so frequently silly, it's very smart as well. Math, science, history, all get referenced. The best parts of the show are the subtle things, those little things in the background or just on screen for a couple of seconds that just make you laugh out loud if you were paying attention. The writers even appear to have been thinking ahead, because if you play close attention to the first episode, you can see a literal shadow of an event revealed seasons later.

app/views/ui/yelp_sign_in.html.haml
%section.sign_in.container
  .row
    .col-sm-10.col-sm-offset-1
      %form.sign_in
        %header
          %h1 Sign in
        %fieldset
          .form-group
            %label Email Address
            .row
              .col-sm-4
                %input.form-control(type="email")
          .form-group
            %label Password
            .row
              .col-sm-4
                %input.form-control(type="password")
        %fieldset.form-group.action
          %input(type="submit" value="Sign in" class="btn btn-default")

app/views/ui/yelp_user.html.haml
%section.user.container
  .row
    .col-sm-10.col-sm-offset-1
      %article
        %header
          %img(src="http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest('knwang@gmail.com'.downcase)}?s=40")
          %h2 Dan's Favorites (3)
        %table.table
          %thead
            %tr
              %th(width="30%") Name
              %th(width="15%") Genre
          %tbody
            - 8.times do
              %tr
                %td
                  = link_to "Taco Joint"
                %td
                  = link_to "Mexican Food"

%section.user_reviews.container
  .row
    .col-sm-10.col-sm-offset-1
      %header
        %h3 Dan's Reviews (253)
      %ul
        - 8.times do
          %article.review
            %li.row
              .col-sm-2
                %p
                  = link_to "\"Taco Joint\""
              .col-sm-8
                %p In my opinion, this is one of the best shows ever made. It's not only funny, but despite being so frequently silly, it's very smart as well. Math, science, history, all get referenced. The best parts of the show are the subtle things, those little things in the background or just on screen for a couple of seconds that just make you laugh out loud if you were paying attention. The writers even appear to have been thinking ahead, because if you play close attention to the first episode, you can see a literal shadow of an event revealed seasons later.

app/views/users/_form.html.haml
%section.register.container
  .row
    .col-sm-10.col-sm-offset-1
      - url = registration ? users_path : login_path
      = bootstrap_form_for @user, url: url, layout: :horizontal, label_errors: true,
      control_col: "col-sm-6" do |f|
        %header
          %h1= registration ? "Register" : "Sign In"
        = f.email_field :email, label: "Email Address"
        = f.password_field :password, label: "Password"
        = f.text_field :full_name, label: "Full Name" if registration
        = f.submit registration ? "Sign Up" : "Sign In", class: "btn btn-default col-sm-offset-2"

app/views/users/new.html.haml
= render "form", registration: true

app/views/users/show.html.haml
%section.user.container
  .row
    .col-sm-10.col-sm-offset-1
      %article
        %header
          %h2= "#{@user.full_name}'s Favorites"
        %table.table
          %thead
            %tr
              %th(width="30%") Name
              %th(width="15%") Genre
          %tbody
            %tr
              %td
                Favorites not implemented yet.
              %td
                Coming soon!

%section.user_reviews.container
  .row
    .col-sm-10.col-sm-offset-1
      %header
        %h3= "#{@user.full_name}'s Reviews (#{@reviews.count})"
      %ul
        - @reviews.each do |review|
          %article.review
            %li.row
              .col-sm-2
                %p
                  = link_to "\"#{review.business.name}\"", business_path(review.business)
              .col-sm-8
                %p= review.description